

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tavrzdb
    username: postgres
    password: postgres
  data:
    mongodb:
      host: localhost
      port: 27017
      database: auditCollateralDB
  rabbitmq:
    host: localhost
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        temp:
          use_jdbc_metadata_defaults: false
  application:
    name: tavrz-cms-audit

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

logging:
  level.ru.fds.tavrzauditcollateral: debug


queue_name:
  audit_new_loan_agreement: queue_audit_new_loan_agreement
  audit_exist_loan_agreement: queue_audit_exist_loan_agreement
  audit_new_pledge_agreement: queue_audit_new_pledge_agreement
  audit_exist_pledge_agreement: queue_audit_exist_pledge_agreement
  audit_new_pledge_subject: queue_audit_new_pledge_subject
  audit_exist_pledge_subject: queue_audit_exist_pledge_subject

description_audit_result:
  loan_agreement:
    date_closed: Кредитный договор не закрыт
    amount: Обеспеченность договора ниже кредитной задолженности
    not_exist_pa: Отсутствуют договоры залога
  pledge_agreement:
    date_closed: Договор залога не закрыт
    not_exist_la: Отсутствуют кредитные договоры
    zero_zs_dz: Залоговая стоимость (по ДЗ) равна нулю
    zero_zs_zz: Залоговая стоимость (по ЗЗ) равна нулю
    not_exist_ps: Отсутствуют предметы залога
  pledge_subject:
    low_liquidity_not_zero_ss: У предмета залога низкая ликвидность и справедливая стоимость больше нуля
    zero_zs_dz: Залоговая стоимость (по ДЗ) равна нулю
    zero_zs_zz: Залоговая стоимость (по ЗЗ) равна нулю
    zero_rs_dz: Рыночная стоимость (по ДЗ) равна нулю
    zero_rs_zz: Рыночная стоимость (по ЗЗ) равна нулю
    zero_ss: Справедливая стоимость равна нулю
    monitoring_overdue: Просрочен мониторинг предмета залога
    conclusion_overdue: Просрочено заключение предмета залога
    losing: Предмет залога утрачен
    not_exist_insurance: Отсутствует договор страхования
    not_exist_encumbrance: Отсутствует обременение в пользу банка
    exist_other_encumbrance: Имеется иные обременения
    insurance_overdue: Срок действия договора страхования истек
    encumbrance_overdue: Срок действия обременения истек



audit_advice:
  loan_agreement:
    date_closed: Закрыть договор; Изменить дату окончания КД; Присвоить статус - Проблемный
    amount: Снизить кредитную задолженность; Предоставить дополнитнльгый залог
    not_exist_pa: Заключить договор залога; Закрыть кредитный договор
  pledge_agreement:
    date_closed: Закрыть договор; Изменить дату ДЗ; Присворить статус - Проблемный
    not_exist_la: Привязать кредитный договор; Закрыть договор залога
    zero_zs_dz: Проверить залоговое заключение. Залоговая стоимость должна быть больше нуля
    zero_zs_zz: Проверить залоговое заключение. Залоговая стоимость должна быть больше нуля
    not_exist_ps: Добавить предметы залога; Закрыть договор залога
  pledge_subject:
    low_liquidity_not_zero_ss: Справедливую стоимость провнять нулю; Пересмостеть степень ликвидности предмета залога
    zero_zs_dz: Вывести из залога; Проверить залоговое заключение. Залоговая стоимость должна быть больше нуля
    zero_zs_zz: Вывести из залога; Проверить залоговое заключение. Залоговая стоимость должна быть больше нуля
    zero_rs_dz: Вывести из залога; Пересмотреть рыночную стоимость
    zero_rs_zz: Вывести из залога; Пересмотреть рыночную стоимость
    zero_ss: Вывести из залога
    monitoring_overdue: Провести мониторинг предмета залога
    conclusion_overdue: Составить заключение предмета залога
    losing: Предоставить ликвидное обеспечение
    not_exist_insurance: Заключить договор страхования
    not_exist_encumbrance: Произвести деиствия по постановке обременения в пользу банка
    exist_other_encumbrance: Снять обременения в польху третьих лиц
    insurance_overdue: Заключить новый договор страхования
    encumbrance_overdue: Произвести деиствия по уточнению сроков действия обременения в пользу банка